version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: examplePassword@123
      POSTGRES_USER: psqlUser
      POSTGRES_DB: vehicleDB
    ports:
      - "5433:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080